In [8]:
from sklearn.datasets import load_digits
from sklearn.model_selection import train_test_split
from sklearn.neural_network import MLPClassifier 
from sklearn.metrics import  confusion_matrix


X, y = load_digits(n_class=2, return_X_y=True) # 'load_digits' dataset contains 10 classes: digits 0 through 9. 'n_class=2' selects only the first 2 digits: 0 and 1. 'return_X_y' returns (data, target) tuple. Unpacked and assigned to variables X, y

print("*zeros and ones only*")
print()
print("feature matrix X:", X.shape) # 360 datapoints with 64 features each
print("target array y:", y.shape) # 360 targets
print()
print()

print("first image:")
print()
print( X[0]) # show first datapoint's feature array. each datapoint is an 8 x 8 pixels grayscale image of a 0 or 1. the features are 64 values from 0 (black) to 16 (white). 
print()
print(y[0]) # show target class label of first datapoint (0)
print()
print(X[0].reshape(8, 8)) # it's easier to make out the digit in the image if we reshape the array to 8 x 8
print()
print()

print("second image:")
print()
print(y[1]) # show target class label of second datapoint (1)
print()
print(X[1].reshape(8, 8)) # second datapoint's feature array (reshaped to 8 x 8)
print()
print()

# *you can view the images directly by plotting them with matplotlib (not shown)*


*zeros and ones only*

feature matrix X: (360, 64)
target array y: (360,)


first image:

[ 0.  0.  5. 13.  9.  1.  0.  0.  0.  0. 13. 15. 10. 15.  5.  0.  0.  3.
 15.  2.  0. 11.  8.  0.  0.  4. 12.  0.  0.  8.  8.  0.  0.  5.  8.  0.
  0.  9.  8.  0.  0.  4. 11.  0.  1. 12.  7.  0.  0.  2. 14.  5. 10. 12.
  0.  0.  0.  0.  6. 13. 10.  0.  0.  0.]

0

[[ 0.  0.  5. 13.  9.  1.  0.  0.]
 [ 0.  0. 13. 15. 10. 15.  5.  0.]
 [ 0.  3. 15.  2.  0. 11.  8.  0.]
 [ 0.  4. 12.  0.  0.  8.  8.  0.]
 [ 0.  5.  8.  0.  0.  9.  8.  0.]
 [ 0.  4. 11.  0.  1. 12.  7.  0.]
 [ 0.  2. 14.  5. 10. 12.  0.  0.]
 [ 0.  0.  6. 13. 10.  0.  0.  0.]]


second image:

1

[[ 0.  0.  0. 12. 13.  5.  0.  0.]
 [ 0.  0.  0. 11. 16.  9.  0.  0.]
 [ 0.  0.  3. 15. 16.  6.  0.  0.]
 [ 0.  7. 15. 16. 16.  2.  0.  0.]
 [ 0.  0.  1. 16. 16.  3.  0.  0.]
 [ 0.  0.  1. 16. 16.  6.  0.  0.]
 [ 0.  0.  1. 16. 16.  6.  0.  0.]
 [ 0.  0.  0. 11. 16. 10.  0.  0.]]




In [9]:
## predicting digits (0 or 1) with neural network 

X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=2) # train/test split

mlp = MLPClassifier() # instantiate model. default one hidden layer with 100 neurons, 'relu' activation. 64 neurons in input layer because dataset has 64 features. 1 neuron in output layer because binary classification. defaults output layer 'logistic' activation because binary classification. therefore, neural network shape is:
#                                    input layer  ->  hidden layer  ->  output layer
#                                    64 neurons       100 neurons       1 neuron
#                                                     relu activation   logistic activation



mlp.fit(X_train, y_train) # fit model 

print("first 5 predictions:", mlp.predict(X_test[0:5])) # first 5 predictions
print("first 5 targets:    ", y_test[0:5]) # first 5 targets (actual values)
print("model accuracy: ", mlp.score(X_test, y_test)) # model accuracy, 100%!


first 5 predictions: [0 1 0 1 1]
first 5 targets:     [0 1 0 1 1]
model accuracy:  1.0


In [10]:
## predicting digits (1 through 9) with neural network

X, y = load_digits(return_X_y=True) # load dataset, this time the whole set 1 through 9, data and targets unpacked and assigned to X, y

X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=2) # train/test split on whole dataset

mlp = MLPClassifier(random_state=3) # instantiate model. default one hidden layer with 100 neurons, 'relu' activation. 64 neurons in input layer because dataset has 64 features. 1 neuron in output layer because binary classification. defaults output layer 'softmax' activation because multilabel classification (10 target labels, digits 0 through 9). therefore, neural network shape is:
#
#                                    input layer  ->  hidden layer  ->  output layer
#                                    64 neurons       100 neurons       10 neurons
#                                                     relu activation   softmax activation
#                                                                       (highest output neuron chosen)

mlp.fit(X_train, y_train) # fit model


print("*all digits, zero through nine*")
print()
print("first 5 predictions:", mlp.predict(X_test[0:5])) # first 5 predictions
print("first 5 targets:    ", y_test[0:5]) # first 5 targets (actual values)
print("model accuracy: ", mlp.score(X_test, y_test)) # model accuracy
print()

# looking at incorrect predictions
y_pred = mlp.predict(X_test) # predictions for all testing datapoints
wrong_pred_mask = (y_pred != y_test) # list of T/F values, T where test predictions don't match test targets
incorrect_pred = y_pred[wrong_pred_mask] # mask applied to predictions, pulls out incorrect predictions 
incorrect_true = y_test[wrong_pred_mask] # mask applied to targets, pulls out actual values for wrong preds
print("wrongly predicted values:", incorrect_true) 
print("wrongly predicted as:    ", incorrect_pred)
print()
# we see the model had the most trouble with 4s and 9s 

# code and comments by github.com/alandavidgrunberg


*all digits, zero through nine*

first 5 predictions: [4 0 9 1 8]
first 5 targets:     [4 0 9 1 4]
model accuracy:  0.96

wrongly predicted values: [4 4 8 4 4 6 9 9 4 3 5 3 9 9 5 5 9 3]
wrongly predicted as:     [8 1 2 8 7 1 5 1 9 8 9 5 7 3 4 1 8 5]

