In [2]:
import numpy as np

x = np.array([[1,2],[3,4],[5,6]])

#   1 2
#   3 4
#   5 6

print(x.sum())
print(x.sum(axis=0))
print(x.sum(axis=1))

21
[ 9 12]
[ 3  7 11]


In [3]:
print(x.min())
print(x.min(axis=0))
print(x.min(axis=1))

1
[1 2]
[1 3 5]


In [4]:
print(x.max())
print(x.max(axis=0))
print(x.max(axis=1))

6
[5 6]
[2 4 6]


In [6]:
print(x.cumsum())
print()
print(x.cumsum(axis=0))
print()
print(x.cumsum(axis=1))

[ 1  3  6 10 15 21]

[[ 1  2]
 [ 4  6]
 [ 9 12]]

[[ 1  3]
 [ 3  7]
 [ 5 11]]


In [7]:
print(x.mean())
print(x.mean(axis=0))
print(x.mean(axis=1))

3.5
[3. 4.]
[1.5 3.5 5.5]


In [8]:
print(x.std())
print(x.std(axis=0))
print(x.std(axis=1))

# code by github.com/alandavidgrunberg

1.707825127659933
[1.63299316 1.63299316]
[0.5 0.5 0.5]
