In [1]:
import numpy as np

a = np.array([[0,1,2],[3,4,5]])
#2x3

b = np.array([1])
#1x1
c = np.array([1,10,100])
#1x3
d = np.array([[1],[10]])
#2x1

print(a+b)
print("")
print(a+c)
print("")
print(a+d)

# code and comments by github.com/alandavidgrunberg

[[1 2 3]
 [4 5 6]]

[[  1  11 102]
 [  4  14 105]]

[[ 1  2  3]
 [13 14 15]]
