In [4]:
import numpy as np

a = np.array([1,2,3])
b = np.array([11,22,33])

a = a.reshape((1,3))
b = b.reshape((1,3))

c = np.concatenate((a,b), axis=0)
print(c.shape)
print(c)
print()
#vstack does the same
#c = np.vstack((a,b))
#print(c.shape)
#print(c)

a = a.reshape((3,1))
b = b.reshape((3,1))

c = np.concatenate((a,b), axis=1)
print(c.shape)
print(c)
#hstack does the same
#c = np.hstack((a,b))
#print(c.shape)
#print(c)

# code and comments by github.com/alandavidgrunberg

(2, 3)
[[ 1  2  3]
 [11 22 33]]

(3, 2)
[[ 1 11]
 [ 2 22]
 [ 3 33]]
