In [6]:
import numpy as np

x = np.array([[1,2,3], [1,9,5], [-1,-2,-3]])

#     1  2  3
#     1  9  5
#    -1 -2 -3

print(x)

[[ 1  2  3]
 [ 1  9  5]
 [-1 -2 -3]]


In [7]:
print(np.cov(x)) #covariance
# unbounded 
# postive number means variables increase in same direction
# negative number means variables change in opposite direction
# 0 means totally unrelated

[[ 1.  2. -1.]
 [ 2. 16. -2.]
 [-1. -2.  1.]]


In [8]:
print(np.corrcoef(x)) #correlation coefficient
# normalized version of coveriance
# between -1 and 1
# 1 means perfectly positively related, 
# -1 means perfectly negatively related
# 0 means totally unrelated

# code and comments by github.com/alandavidgrunberg

[[ 1.   0.5 -1. ]
 [ 0.5  1.  -0.5]
 [-1.  -0.5  1. ]]
